services:
  # Service API (Backend)
  - type: web
    name: youtube-monitor-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    
  # Service Frontend (React)
  - type: web
    name: youtube-monitor-client
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: youtube-monitor-api
          type: web
          property: url
        value: https://youtube-monitor-api.onrender.com/api
